### ISSUE TITLE
How to DEG analysis based on the output of fastq2EZbakR of EZbakR?

### ISSUE THREAD

**Issue by realzhang** [isaacvock/EZbakR#12]
Dear author,
I've done some 4sU labeling for WT and Mutant cells together with no-4sU controls, and also ran fastq2EZbakR and QC of EZbakR.
But I am still confused about how to do DEG analysis, which are supposed to be no change in steady RNAs and decrease in nascent RNAs.
Please kindly let me know which part of the output can be used to do DEG analysis. If in Slam-Dunk, I can use the Tcount file. I am confused about the output. I found no description in the documents.
Best wishes!

**Comment by isaacvock** [comment]
Hello,

That analysis strategy is not implemented in EZbakR because I have concerns about its rigor and interpretation. Below I will explain my gripes with interpreting differential expression analysis of new read counts, but here is how you can generate the various read count matrices you would require for this analysis (ezbdo is your EZbakRData object, on which you should have at least run `EstimateFractions`. I am also assuming s4U pulse labeling, in which case the relevant column in the fractions table is `fraction_highTC`. These assumptions can easily be altered as necessary):

```
library(dplyr)
library(tidyr)

### Count matrix of new reads
count_df <- EZget(ezbdo, type = "fractions") %>%
  mutate(new_reads = n*fraction_highTC) %>%
  dplyr::select(sample, XF, new_reads) %>%
  pivot_wider(names_from = sample,
              values_from = new_reads)

### Count matrix of old reads
count_df <- EZget(ezbdo, type = "fractions") %>%
  mutate(old_reads = n*(1-fraction_highTC)) %>%
  dplyr::select(sample, XF, old_reads) %>%
  pivot_wider(names_from = sample,
              values_from = old_reads)


### Count matrix of all reads
count_df <- EZget(ezbdo, type = "fractions") %>%
  dplyr::select(sample, XF, n) %>%
  pivot_wider(names_from = sample,
              values_from = n)
```

These "count matrices" are technically data frames with one column per sample as well as feature column(s) (in this case XF, though you could change that in the code above to use whatever feature or set of features from the analysis you would like). These can readily be converted into count matrices and passed to DESeq2 or any other differential expression analysis software.

Why I don't like performing DEG analysis on nascent and total/old RNA:

The second SLAM-seq paper ([2018 Science paper](https://pmc.ncbi.nlm.nih.gov/articles/PMC6409205/)) popularized the notion that SLAM-seq data can be interpreted as a transcriptional assay, as well as the idea of performing differential expression analysis on nascent read counts. Both of these are misguided for the same reason: the label times typically used for a SLAM-seq experiment mean that the nascent read counts are a function of both transcription and degradation kinetics, not just the former. In that study, a 1 hour label time was used, and many studies performing similar analyses have used the same label time. In most mammalian cell lines, the average RNA half-life is around 4 hours. That means, that after 1 hour of labeling, there is a non-trivial amount of degradation of RNA synthesized during the label time. The assumption of negligible degradation of nascent RNA is likely only a good assumption if you go for a much shorter label time (e.g., 10 minutes). A similar argument against this interpretation was made in the [grandR manuscript](https://www.nature.com/articles/s41467-023-39163-4).

Instead, EZbakR supports a more rigorous kinetic interpretation of NR-seq data. Given a model of RNA dynamics (e.g., 0 -> M -> 0, like in Figure 5A of the [EZbakR preprint](https://www.biorxiv.org/content/10.1101/2024.10.14.617411v1)), EZbakR estimates the kinetic parameters of that model (e.g., synthesis and degradation kinetics in a standard mature RNA SLAM-seq analysis, the default in EZbakR). EZbakR then supports performing comparative analyses of these kinetic parameters across biological conditions, as detailed in the documentation. Complications like violation of the steady-state assumption can also be dealt with in this framework (as discussed in the [documentation](https://isaacvock.github.io/EZbakR/articles/EstimateKinetics.html#non-steady-state-nss-analyses)).

Aside: part of what has made the DEG analysis of nascent RNA so popular is how convincingly it seems to improve upon total RNA DEG in thee aforementioned 2018 paper. Part of the reason the total RNA DEG is not able to capture the expected global decrease in RNA levels though is because they did not properly normalize their data. DESeq2 (and most other DE software) by default calculates normalization factors by assuming that the total levels of RNA are the same across all conditions. More specifically, they typically set the median read count (or a more robust variant of the median) equal across all conditions. If your perturbation is like that from the 2018 SLAM-seq paper (i.e., global transcriptional inhibition), this assumption is not met and the normalization will remove the global downregulation signal. If they had spike-in normalized their RNA-seq data, the total and nascent DEG analysis would have likely shown the same thing. In addition, I have concerns with several aspects of their nascent RNA analysis, but that has more to do with the strategy of counting nascent reads based on simple mutational cutoffs, a strategy limited for reasons discussed in the EZbakR preprint (see Supplemental Figure S1 for example, and my discussion of the limitations of this analysis method [here](https://github.com/erhard-lab/grandR/issues/30)).

Best,
Isaac
